import type { EvidenceRecord, VerificationReport } from '../domain/schemas.js';

const STATUS_ICON = {
  VERIFIED: '✅',
  SUPPORTED: '🔵',
  UNVERIFIED: '⚪',
  FAILED: '❌',
  HUMAN_REVIEW_REQUIRED: '⚠️',
  NOT_APPLICABLE: '➖',
} as const;

const VERDICT_ICON = {
  VERIFIED: '✅',
  NEEDS_REVIEW: '⚠️',
  VERIFICATION_FAILED: '⛔',
  INSUFFICIENT_EVIDENCE: '🔎',
} as const;

export function renderMarkdownReport(report: VerificationReport): string {
  const evidence = new Map(report.evidence.map((record) => [record.id, record]));
  const lines: string[] = [
    '# TaskWitness Report',
    '',
    `> ${VERDICT_ICON[report.verdict]} **${humanize(report.verdict)}**`,
    '',
    '## Task',
    '',
    report.task,
    '',
    '## Verdict',
    '',
    ...report.verdictReasons.map((reason) => `- ${reason}`),
    '',
    '## Requirements',
    '',
  ];

  for (const finding of report.requirements) {
    lines.push(
      `### ${STATUS_ICON[finding.status]} ${finding.requirementId} — ${finding.text}`,
      '',
      `**Status:** ${humanize(finding.status)} · **Proof strength:** ${finding.strength}/3`,
      '',
      finding.explanation,
      '',
    );
    const records = finding.evidenceIds
      .map((id) => evidence.get(id))
      .filter((record): record is EvidenceRecord => record !== undefined);
    if (records.length === 0) lines.push('_Evidence: none._', '');
    else {
      lines.push('Evidence:', '');
      for (const record of records) lines.push(`- **${record.id}** — ${record.summary}`);
      lines.push('');
    }
  }

  lines.push(
    '## What changed',
    '',
    '| Files | Added | Modified | Deleted | Renamed | Lines + | Lines - |',
    '| ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
    `| ${report.changeSummary.filesChanged} | ${report.changeSummary.added} | ${report.changeSummary.modified} | ${report.changeSummary.deleted} | ${report.changeSummary.renamed} | ${report.changeSummary.additions} | ${report.changeSummary.deletions} |`,
    '',
    '| File | Change | Classification | Lines |',
    '| --- | --- | --- | ---: |',
    ...report.changes.map(
      (change) =>
        `| \`${escapeTable(change.path)}\` | ${change.status} | ${humanize(change.classification)} | +${change.additions ?? 'binary'} / -${change.deletions ?? 'binary'} |`,
    ),
    '',
    '## Verification',
    '',
  );
  if (report.verificationChecks.length === 0)
    lines.push('_No verification commands were run._', '');
  else {
    lines.push('| Check | Command | Result | Duration |', '| --- | --- | --- | ---: |');
    for (const check of report.verificationChecks) {
      lines.push(
        `| ${check.label} | \`${escapeTable(check.command)}\` | ${check.status === 'passed' ? '✅' : '❌'} ${check.status} | ${check.durationMs} ms |`,
      );
    }
    lines.push('');
  }

  if (report.warnings.length > 0) {
    lines.push('## Human review', '');
    for (const warning of report.warnings) {
      lines.push(
        `### ${warning.severity === 'high' ? '🚨' : '⚠️'} ${warning.title}`,
        '',
        warning.message,
        '',
        ...warning.files.map((file) => `- \`${file}\``),
        '',
      );
    }
  }

  lines.push(
    '<details>',
    '<summary>Known limitations</summary>',
    '',
    ...report.limitations.map((limitation) => `- ${limitation}`),
    '',
    '</details>',
    '',
    '---',
    '',
    `_Generated by TaskWitness ${report.taskWitnessVersion}. Evidence IDs resolve in \`evidence.json\`._`,
    '',
  );
  return lines.join('\n');
}

function humanize(value: string): string {
  return value.replaceAll('_', ' ');
}

function escapeTable(value: string): string {
  return value.replaceAll('|', '\\|');
}
